/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan.java;

import javax.swing.JPanel;

/**
 *
 * @author Hoang Nguyen
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("QUẢN LÍ ĐƠN HÀNG");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_hethong = new javax.swing.JMenu();
        menu_hethong_thoat = new javax.swing.JMenuItem();
        menu_khachhang = new javax.swing.JMenu();
        menu_khachhang_them = new javax.swing.JMenuItem();
        menu_khachhang_sua = new javax.swing.JMenuItem();
        menu_khachhang_timkiem = new javax.swing.JMenuItem();
        menu_sanpham = new javax.swing.JMenu();
        menu_sanpham_them = new javax.swing.JMenuItem();
        menu_sanpham_sua = new javax.swing.JMenuItem();
        menu_sanpham_timkiem = new javax.swing.JMenuItem();
        menu_hoadon = new javax.swing.JMenu();
        menu_hoadon_thanhtoan = new javax.swing.JMenuItem();
        menu_hoadon_quanli = new javax.swing.JMenuItem();
        menu_hoadon_thongke = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMain.setBackground(new java.awt.Color(0, 153, 153));
        panelMain.setPreferredSize(new java.awt.Dimension(100, 100));
        panelMain.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\15291415035b24d8ff405d2.jpg")); // NOI18N
        panelMain.add(jLabel2, java.awt.BorderLayout.CENTER);

        menu_hethong.setText("Hệ thống");

        menu_hethong_thoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.CTRL_MASK));
        menu_hethong_thoat.setText("Thoát");
        menu_hethong_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_hethong_thoatActionPerformed(evt);
            }
        });
        menu_hethong.add(menu_hethong_thoat);

        jMenuBar1.add(menu_hethong);

        menu_khachhang.setText("Khách Hàng");

        menu_khachhang_them.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menu_khachhang_them.setText("Thêm");
        menu_khachhang_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_khachhang_themActionPerformed(evt);
            }
        });
        menu_khachhang.add(menu_khachhang_them);

        menu_khachhang_sua.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_khachhang_sua.setText("Sửa");
        menu_khachhang_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_khachhang_suaActionPerformed(evt);
            }
        });
        menu_khachhang.add(menu_khachhang_sua);

        menu_khachhang_timkiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menu_khachhang_timkiem.setText("Tìm kiếm");
        menu_khachhang_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_khachhang_timkiemActionPerformed(evt);
            }
        });
        menu_khachhang.add(menu_khachhang_timkiem);

        jMenuBar1.add(menu_khachhang);

        menu_sanpham.setText("Sản Phẩm");

        menu_sanpham_them.setText("Thêm");
        menu_sanpham_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sanpham_themActionPerformed(evt);
            }
        });
        menu_sanpham.add(menu_sanpham_them);

        menu_sanpham_sua.setText("Sửa");
        menu_sanpham_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sanpham_suaActionPerformed(evt);
            }
        });
        menu_sanpham.add(menu_sanpham_sua);

        menu_sanpham_timkiem.setText("Tìm kiếm");
        menu_sanpham_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sanpham_timkiemActionPerformed(evt);
            }
        });
        menu_sanpham.add(menu_sanpham_timkiem);

        jMenuBar1.add(menu_sanpham);

        menu_hoadon.setText("Hóa Đơn");

        menu_hoadon_thanhtoan.setText("Tạm tính");
        menu_hoadon_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_hoadon_thanhtoanActionPerformed(evt);
            }
        });
        menu_hoadon.add(menu_hoadon_thanhtoan);

        menu_hoadon_quanli.setText("Quản Lí đơn hàng");
        menu_hoadon_quanli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_hoadon_quanliActionPerformed(evt);
            }
        });
        menu_hoadon.add(menu_hoadon_quanli);

        menu_hoadon_thongke.setText("Thống kê");
        menu_hoadon_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_hoadon_thongkeActionPerformed(evt);
            }
        });
        menu_hoadon.add(menu_hoadon_thongke);

        jMenuBar1.add(menu_hoadon);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showPanel(JPanel panel){
        panelMain.removeAll();
        panelMain.add(panel);
        panelMain.validate();
    }
    
    private void menu_hethong_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_hethong_thoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_hethong_thoatActionPerformed

    private void menu_khachhang_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_khachhang_themActionPerformed
        this.showPanel(new PanelThemKhachHang());
    }//GEN-LAST:event_menu_khachhang_themActionPerformed

    private void menu_khachhang_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_khachhang_suaActionPerformed
        this.showPanel(new PanelSuaKhachHang());
    }//GEN-LAST:event_menu_khachhang_suaActionPerformed

    private void menu_khachhang_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_khachhang_timkiemActionPerformed
        this.showPanel(new PanelTimKiemKhachHang());
    }//GEN-LAST:event_menu_khachhang_timkiemActionPerformed

    private void menu_sanpham_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sanpham_timkiemActionPerformed
        this.showPanel(new PanelTimKiemSanPham());
    }//GEN-LAST:event_menu_sanpham_timkiemActionPerformed

    private void menu_hoadon_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_hoadon_thanhtoanActionPerformed
        this.showPanel(new PanelDonHang());
    }//GEN-LAST:event_menu_hoadon_thanhtoanActionPerformed

    private void menu_hoadon_quanliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_hoadon_quanliActionPerformed
        this.showPanel(new PanelQuanLiDonHang());
    }//GEN-LAST:event_menu_hoadon_quanliActionPerformed

    private void menu_sanpham_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sanpham_themActionPerformed
        this.showPanel(new PanelThemSanPham());
    }//GEN-LAST:event_menu_sanpham_themActionPerformed

    private void menu_sanpham_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sanpham_suaActionPerformed
        this.showPanel(new PanelSuaSanPham());
    }//GEN-LAST:event_menu_sanpham_suaActionPerformed

    private void menu_hoadon_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_hoadon_thongkeActionPerformed
        this.showPanel(new PanelThongKe());
    }//GEN-LAST:event_menu_hoadon_thongkeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_hethong;
    private javax.swing.JMenuItem menu_hethong_thoat;
    private javax.swing.JMenu menu_hoadon;
    private javax.swing.JMenuItem menu_hoadon_quanli;
    private javax.swing.JMenuItem menu_hoadon_thanhtoan;
    private javax.swing.JMenuItem menu_hoadon_thongke;
    private javax.swing.JMenu menu_khachhang;
    private javax.swing.JMenuItem menu_khachhang_sua;
    private javax.swing.JMenuItem menu_khachhang_them;
    private javax.swing.JMenuItem menu_khachhang_timkiem;
    private javax.swing.JMenu menu_sanpham;
    private javax.swing.JMenuItem menu_sanpham_sua;
    private javax.swing.JMenuItem menu_sanpham_them;
    private javax.swing.JMenuItem menu_sanpham_timkiem;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
