/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan.java;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoang Nguyen
 */
public class PanelQuanLiDonHang extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuangLiDonHang
     */
    public PanelQuanLiDonHang() {
        initComponents();
        loadSanPhamToTenSanphamCB();
        loadDataFromGioHang("SELECT * FROM giohang WHERE trangthai='Đã thanh Toán' Order by tensanpham");
    }

    private String header[] = {"STT", "Mã đơn hàng", "Tên khách hàng", "Số Điện Thoại", "Loại khách hàng", "Tên sản phẩm", "Mã sản phẩm", "Đơn giá", "Số lượng", "Trạng thái"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);

    private String header2[] = {"Tên khách hàng", "Số Điện Thoại"};
    private DefaultTableModel tblModel2 = new DefaultTableModel(header, 0);

    ArrayList<ClassSanPham> spList = new ArrayList<>();

    public void updateDataIntoDonHang(String sql) {
        try {
            Connection conn = new dbconnection().connectionDB();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to DB", JOptionPane.INFORMATION_MESSAGE);
            }

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, this.lb_madonhang.getText());
            pst.setString(2, this.lb_tenkhachhang.getText());
            pst.setString(3, this.lb_sdt.getText());
            pst.setString(4, this.lb_loaikhachhang.getText());
            pst.setString(5, this.cb_tensanpham.getSelectedItem().toString());
            pst.setString(6, this.lb_masanpham.getText());
            pst.setString(7, this.lb_dongia.getText());
            pst.setString(8, this.txt_soluong.getText());
            JOptionPane.showMessageDialog(this, "Updated success", "Message", JOptionPane.INFORMATION_MESSAGE);
            pst.executeUpdate();
            conn.close();
        } catch (Exception e) {
        }
    }

    public void updateDaThanhToanIntoDonHang() {
        try {
            Connection conn = new dbconnection().connectionDB();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to DB", JOptionPane.INFORMATION_MESSAGE);
            }
            String value = (tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 1).toString());
            String sql = "UPDATE giohang SET trangthai= ? WHERE madonhang='" + value + "'";
            System.out.println(sql);

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, "Đã thanh toán");
            JOptionPane.showMessageDialog(this, "Đã thanh toán thành công", "Giao dịch", JOptionPane.INFORMATION_MESSAGE);
            pst.executeUpdate();
            conn.close();
        } catch (Exception e) {
        }
    }

    public void loadSanPhamToTenSanphamCB() {
        try {
            Connection connection = new dbconnection().connectionDB();
            String loaiCB = "SELECT * FROM sanpham";
            PreparedStatement pst = connection.prepareStatement(loaiCB);
            ResultSet rs = pst.executeQuery();
            spList = new ArrayList<>();
            while (rs.next()) {
                ClassSanPham sp = new ClassSanPham();
                sp.setMasanpham(rs.getNString("masanpham"));
                sp.setLoai(rs.getNString("loai"));
                sp.setTensanpham(rs.getNString("tensanpham"));
                sp.setDongia(rs.getInt("dongia"));
                spList.add(sp);
                cb_tensanpham.addItem(sp.getTensanpham());
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ArrayList<ClassDonHang> dhList = new ArrayList<>();

    public void selectDataFromGioHang() {
        try {
            Connection connection = new dbconnection().connectionDB();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to database", JOptionPane.INFORMATION_MESSAGE);
            }
            Statement st = connection.createStatement();

            String sql = "SELECT * FROM giohang WHERE madonhang='" + lb_madonhang.getText() + "'";

            ResultSet rs = st.executeQuery(sql);

            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Message", "Not Data!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            dhList = new ArrayList<>();
            while (rs.next()) {
                ClassDonHang data = new ClassDonHang();
                data.setStt(rs.getInt("stt"));
                data.setMadonhang(rs.getString("madonhang"));
                data.setTenkhachhang(rs.getString("tenkhachhang"));
                data.setSdtkhachhang(rs.getString("sdtkhachhang"));
                data.setLoaikhachhang(rs.getString("loaikhachhang"));
                data.setTensanpham(rs.getString("tensanpham"));
                data.setMasanpham(rs.getString("masanpham"));
                data.setDongia(rs.getInt("dongia"));
                data.setSoluong(rs.getInt("soluong"));
                data.setTrangthai(rs.getString("trangthai"));
                dhList.add(data);
            }

            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void searchDataFromKhachHang(String sql) {
        try {
            Connection connection = new dbconnection().connectionDB();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Error connect to database", "Message", JOptionPane.INFORMATION_MESSAGE);
            }

            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Khách hàng chưa tồn tại, vui lòng thêm mới", "Message", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            tblModel = new DefaultTableModel(header2, 0);
            Vector data = null;
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getString("tenkhachhang"));
                data.add(rs.getString("sdtkhachhang"));
                tblModel.addRow(data);
            }
            tb_khachhang.setModel(tblModel);
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Not Found!", "Message", JOptionPane.INFORMATION_MESSAGE);
            e.printStackTrace();
        }
    }

    public void loadDataFromGioHang(String sql) {
        try {
            Connection connection = new dbconnection().connectionDB();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Error connect to database", "Message", JOptionPane.INFORMATION_MESSAGE);
            }
            Statement st = connection.createStatement();

//            String sql = "select * from giohang";
            ResultSet rs = st.executeQuery(sql);

            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Không có dữ liệu!", "Message", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            tblModel = new DefaultTableModel(header, 0);
            Vector data = null;
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getInt("stt"));
                data.add(rs.getString("madonhang"));
                data.add(rs.getString("tenkhachhang"));
                data.add(rs.getString("sdtkhachhang"));
                data.add(rs.getString("loaikhachhang"));
                data.add(rs.getString("tensanpham"));
                data.add(rs.getString("masanpham"));
                data.add(rs.getInt("dongia"));
                data.add(rs.getInt("soluong"));
                data.add(rs.getString("trangthai"));
                tblModel.addRow(data);
            }
            tb_giohangpanel_thongtindonhang.setModel(tblModel);
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void deleteDataInKhachHang(String sql) {
        try {
            Connection conn = new dbconnection().connectionDB();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to DB", JOptionPane.INFORMATION_MESSAGE);
            }
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.executeUpdate();
//            DefaultTableModel model =(DefaultTableModel)spList.getClass();
//            model.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Delete success", "Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_giohangpanel_thongtindonhang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_madonhang = new javax.swing.JLabel();
        lb_tenkhachhang = new javax.swing.JLabel();
        lb_loaikhachhang = new javax.swing.JLabel();
        cb_tensanpham = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_masanpham = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_sdt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_trangthai = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        lb_dongia = new javax.swing.JLabel();
        btn_xuat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cb_timkiem = new javax.swing.JComboBox<>();
        txt_timkiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_tim = new javax.swing.JButton();
        btn_get = new javax.swing.JButton();
        lb_timkiemtenkhachhang = new javax.swing.JLabel();
        lb_timkiemsdt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_khachhang = new javax.swing.JTable();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_thanhtoan = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        tb_giohangpanel_thongtindonhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_giohangpanel_thongtindonhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_giohangpanel_thongtindonhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_giohangpanel_thongtindonhang);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Mã đơn hàng:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Tên khách hàng:");

        lb_madonhang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_madonhang.setForeground(new java.awt.Color(0, 0, 102));
        lb_madonhang.setText("________");

        lb_tenkhachhang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_tenkhachhang.setForeground(new java.awt.Color(0, 0, 102));
        lb_tenkhachhang.setText("_________");

        lb_loaikhachhang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_loaikhachhang.setForeground(new java.awt.Color(0, 0, 102));
        lb_loaikhachhang.setText("Khách hàng");

        cb_tensanpham.setBackground(new java.awt.Color(204, 255, 204));
        cb_tensanpham.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_tensanpham.setForeground(new java.awt.Color(255, 0, 0));
        cb_tensanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_tensanphamMouseClicked(evt);
            }
        });
        cb_tensanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tensanphamActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Tên sản phẩm:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Mã sản phẩm:");

        lb_masanpham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_masanpham.setForeground(new java.awt.Color(255, 51, 51));
        lb_masanpham.setText("___");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText("Số điện thoại:");

        lb_sdt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_sdt.setForeground(new java.awt.Color(0, 0, 102));
        lb_sdt.setText("_________");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Trạng thái:");

        lb_trangthai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_trangthai.setForeground(new java.awt.Color(0, 0, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Đơn giá:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Số lượng:");

        lb_dongia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lb_dongia.setForeground(new java.awt.Color(0, 0, 102));
        lb_dongia.setText("$$$");

        btn_xuat.setBackground(new java.awt.Color(51, 51, 51));
        btn_xuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_xuat.setForeground(new java.awt.Color(255, 255, 255));
        btn_xuat.setText("Xuất");
        btn_xuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_sdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_tenkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_tensanpham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lb_madonhang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_xuat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38)
                        .addComponent(lb_dongia)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lb_trangthai))
                    .addComponent(lb_loaikhachhang)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lb_masanpham)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_madonhang)
                    .addComponent(jLabel7)
                    .addComponent(lb_trangthai)
                    .addComponent(btn_xuat))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_tenkhachhang)
                    .addComponent(lb_loaikhachhang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_sdt))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_tensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lb_masanpham))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_dongia))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        cb_timkiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_timkiem.setForeground(new java.awt.Color(255, 0, 0));
        cb_timkiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên khách hàng", "Số điện thoại" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setText("Tìm kiếm:");

        btn_tim.setBackground(new java.awt.Color(102, 153, 255));
        btn_tim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_tim.setForeground(new java.awt.Color(255, 102, 102));
        btn_tim.setText("Tìm");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        btn_get.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_get.setForeground(new java.awt.Color(51, 51, 255));
        btn_get.setText("Lấy dữ liệu");
        btn_get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_getActionPerformed(evt);
            }
        });

        lb_timkiemtenkhachhang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_timkiemtenkhachhang.setForeground(new java.awt.Color(102, 102, 255));
        lb_timkiemtenkhachhang.setText("Tên khách hàng");

        lb_timkiemsdt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_timkiemsdt.setForeground(new java.awt.Color(102, 102, 255));
        lb_timkiemsdt.setText("Số điện thoại");

        tb_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tb_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_khachhangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_khachhang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_timkiemtenkhachhang)
                        .addGap(25, 25, 25)
                        .addComponent(lb_timkiemsdt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_get)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tim))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_timkiemtenkhachhang)
                    .addComponent(lb_timkiemsdt)
                    .addComponent(btn_get))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(0, 102, 255));
        btn_sua.setText("Sửa ");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(0, 102, 255));
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_thanhtoan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_thanhtoan.setForeground(new java.awt.Color(0, 102, 255));
        btn_thanhtoan.setText("Thanh Toán");
        btn_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thanhtoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_giohangpanel_thongtindonhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_giohangpanel_thongtindonhangMouseClicked

        lb_madonhang.setText(tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 1).toString());
        lb_tenkhachhang.setText(tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 2).toString());
        lb_sdt.setText(tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 3).toString());
        lb_loaikhachhang.setText(tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 4).toString());
        cb_tensanpham.setSelectedItem(tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 5).toString());
        lb_masanpham.setText(tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 6).toString());
        lb_dongia.setText(tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 7).toString());
        txt_soluong.setText(tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 8).toString());
        lb_trangthai.setText(tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 9).toString());
    }//GEN-LAST:event_tb_giohangpanel_thongtindonhangMouseClicked

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        if (cb_timkiem.getSelectedItem().toString().equals("Tên khách hàng")) {
            String sql = "SELECT * FROM khachhang WHERE tenkhachhang LIKE '%" + txt_timkiem.getText() + "%'";
            this.searchDataFromKhachHang(sql);

        } else if (cb_timkiem.getSelectedItem().toString().equals("Số điện thoại")) {
            String sql = "SELECT * FROM khachhang WHERE sdtkhachhang LIKE '%" + txt_timkiem.getText() + "%'";
            this.searchDataFromKhachHang(sql);
        }
    }//GEN-LAST:event_btn_timActionPerformed

    private void cb_tensanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_tensanphamMouseClicked

    }//GEN-LAST:event_cb_tensanphamMouseClicked

    private void cb_tensanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tensanphamActionPerformed
        ClassSanPham sp = spList.get(cb_tensanpham.getSelectedIndex());

        this.lb_masanpham.setText(sp.getMasanpham().toString());
        this.lb_dongia.setText(Integer.toString(sp.getDongia()));
    }//GEN-LAST:event_cb_tensanphamActionPerformed

    private void tb_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_khachhangMouseClicked
        lb_timkiemtenkhachhang.setText(tb_khachhang.getValueAt(tb_khachhang.getSelectedRow(), 0).toString());
        lb_timkiemsdt.setText(tb_khachhang.getValueAt(tb_khachhang.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tb_khachhangMouseClicked

    private void btn_getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_getActionPerformed
        String sql = "SELECT * FROM giohang WHERE sdtkhachhang ='" + lb_timkiemsdt.getText() + "' AND tenkhachhang= '" + lb_timkiemtenkhachhang.getText() + "'";
        this.loadDataFromGioHang(sql);
        System.out.println(sql);
    }//GEN-LAST:event_btn_getActionPerformed

    private void btn_xuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuatActionPerformed
        String sql = "SELECT * FROM giohang WHERE madonhang ='" + lb_madonhang.getText() + "'";
        this.loadDataFromGioHang(sql);
        System.out.println(sql);
    }//GEN-LAST:event_btn_xuatActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        if (lb_trangthai.getText().toString().equals("Đã thanh toán")) {
            JOptionPane.showMessageDialog(this, "Đơn hàng đã được thanh toán, không thể chỉnh sửa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String value = (tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 0).toString());
            String sql = "UPDATE giohang SET madonhang=?,tenkhachhang=?,sdtkhachhang=?,loaikhachhang=?,tensanpham=?, masanpham=?, dongia=?, soluong=? WHERE stt=" + value;
            System.out.println(sql);
            this.updateDataIntoDonHang(sql);

            String sql2 = "SELECT * FROM giohang WHERE madonhang ='" + lb_madonhang.getText() + "'";
            this.loadDataFromGioHang(sql2);
        }

    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        if (lb_trangthai.getText().toString().equals("Đã thanh toán")) {
            String value = (tb_giohangpanel_thongtindonhang.getValueAt(tb_giohangpanel_thongtindonhang.getSelectedRow(), 0).toString());
            String sql = "DELETE FROM giohang WHERE stt='" + value + "'";
            this.deleteDataInKhachHang(sql);
            System.out.println(sql);

            String sql2 = "SELECT * FROM giohang WHERE madonhang ='" + lb_madonhang.getText() + "'";
            this.loadDataFromGioHang(sql2);
        } else {
            JOptionPane.showMessageDialog(this, "Đơn hàng chưa được thanh toán, không thể xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thanhtoanActionPerformed
        if (lb_trangthai.getText().toString().equals("Tạm tính")) {
            int kq = 0;
            this.selectDataFromGioHang();
            for (ClassDonHang dh : dhList) {
                kq += dh.Thanhtien();
            }
            if (lb_loaikhachhang.getText().toString().equals("Khách hàng thân thiết")) {
                kq = kq - kq * 15 / 100;
            }
            if (lb_loaikhachhang.getText().toString().equals("Khách hàng VIP")) {
                kq = kq - kq * 10 / 100;
            }
            JOptionPane.showMessageDialog(this, "Số tiền phải trả: " + kq, "Thanh toán", JOptionPane.INFORMATION_MESSAGE);

            updateDaThanhToanIntoDonHang();
            String sql2 = "SELECT * FROM giohang WHERE madonhang ='" + lb_madonhang.getText() + "'";
            this.loadDataFromGioHang(sql2);
        } else {
            JOptionPane.showMessageDialog(this, "Đơn hàng đã được thanh toán", "Thanh toán", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_thanhtoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_get;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_thanhtoan;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btn_xuat;
    private javax.swing.JComboBox<String> cb_tensanpham;
    private javax.swing.JComboBox<String> cb_timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_dongia;
    private javax.swing.JLabel lb_loaikhachhang;
    private javax.swing.JLabel lb_madonhang;
    private javax.swing.JLabel lb_masanpham;
    private javax.swing.JLabel lb_sdt;
    private javax.swing.JLabel lb_tenkhachhang;
    private javax.swing.JLabel lb_timkiemsdt;
    private javax.swing.JLabel lb_timkiemtenkhachhang;
    private javax.swing.JLabel lb_trangthai;
    private javax.swing.JTable tb_giohangpanel_thongtindonhang;
    private javax.swing.JTable tb_khachhang;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
