/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan.java;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *  
 * @author Hoang Nguyen
 */
public class PanelSuaSanPham extends javax.swing.JPanel {
    private DefaultListModel listModel = new DefaultListModel();
    /**
     * Creates new form PanelSuaKhachHang
     */
    public PanelSuaSanPham() {
        initComponents();
        this.searchDataFromSanPham();
        for (ClassSanPham sp : spList) {
            listModel.addElement(sp.getMasanpham().toString());
            this.tbl_table.setModel(listModel);
        }
    }
    ArrayList<ClassSanPham> spList = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_suapanel = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_table = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        btn_suapanel_hoantat = new javax.swing.JButton();
        txt_dongia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_suapanel_xoa = new javax.swing.JButton();
        lb_masanpham = new javax.swing.JLabel();
        txt_loai = new javax.swing.JTextField();
        txt_tensanpham = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        cb_suapanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_suapanel.setForeground(new java.awt.Color(153, 0, 0));
        cb_suapanel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sản phẩm", "Tên sản phẩm", "Đơn giá" }));
        cb_suapanel.setToolTipText("");
        cb_suapanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_suapanelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Danh Mục");

        tbl_table.setBackground(new java.awt.Color(255, 153, 153));
        tbl_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_table.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tbl_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_table);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        btn_suapanel_hoantat.setBackground(new java.awt.Color(153, 204, 255));
        btn_suapanel_hoantat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_suapanel_hoantat.setForeground(new java.awt.Color(51, 0, 255));
        btn_suapanel_hoantat.setText("Hoàn tất");
        btn_suapanel_hoantat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suapanel_hoantatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Tên sản phẩm");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Loại sản phẩm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Đơn giá");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Mã sản phẩm");

        btn_suapanel_xoa.setBackground(new java.awt.Color(153, 204, 255));
        btn_suapanel_xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_suapanel_xoa.setForeground(new java.awt.Color(51, 0, 255));
        btn_suapanel_xoa.setText("Xóa");
        btn_suapanel_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suapanel_xoaActionPerformed(evt);
            }
        });

        lb_masanpham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_masanpham.setForeground(new java.awt.Color(0, 0, 255));
        lb_masanpham.setText("!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_suapanel_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(btn_suapanel_hoantat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(85, 85, 85)
                        .addComponent(txt_dongia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(txt_tensanpham))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_masanpham)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_loai))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lb_masanpham))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_tensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_suapanel_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suapanel_hoantat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_suapanel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(81, 81, 81)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(cb_suapanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateDataIntoSanPham(String sql){
        try {
            Connection connection = new dbconnection().connectionDB();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to DB", JOptionPane.INFORMATION_MESSAGE);
            }            
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, this.lb_masanpham.getText());
            pst.setString(2, this.txt_loai.getText());
            pst.setString(3, this.txt_tensanpham.getText());
            pst.setString(4, this.txt_dongia.getText());
            JOptionPane.showMessageDialog(this, "Updated success", "Message", JOptionPane.INFORMATION_MESSAGE);
            pst.executeUpdate();
            connection.close();
        } catch (Exception e) {
        }
    }
    
    public void searchDataFromSanPham() {
        try {
            Connection connection = new dbconnection().connectionDB();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to database", JOptionPane.INFORMATION_MESSAGE);
            }
            Statement st = connection.createStatement();
            
            String sql= "SELECT * FROM sanpham ORDER BY masanpham";
            
            ResultSet rs = st.executeQuery(sql);

            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Message", "Not Data!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            while (rs.next()) {
                ClassSanPham data = new ClassSanPham();                
                data.setMasanpham(rs.getString("masanpham"));
                data.setLoai(rs.getString("loai"));
                data.setTensanpham(rs.getString("tensanpham"));
                data.setDongia(rs.getInt("dongia"));
                spList.add(data);
            }
            
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void deleteDataInKhachHang(String sql){
        try {
            Connection conn = new dbconnection().connectionDB();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to DB", JOptionPane.INFORMATION_MESSAGE);
            }
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.executeUpdate();
//            DefaultTableModel model =(DefaultTableModel)spList.getClass();
//            model.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Delete success", "Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }
    
    private void cb_suapanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_suapanelActionPerformed
        listModel.clear();

        spList.clear();
        this.searchDataFromSanPham();
        tbl_table.setModel(listModel);
        for (ClassSanPham sp : spList) {
            if(cb_suapanel.getSelectedItem().toString().equals("Mã sản phẩm")){
                listModel.addElement(sp.getMasanpham().toString());
                this.tbl_table.setModel(listModel);
            }else if(cb_suapanel.getSelectedItem().toString().equals("Tên sản phẩm")){
                listModel.addElement(sp.getTensanpham().toString());
                this.tbl_table.setModel(listModel);
            }
            else if(cb_suapanel.getSelectedItem().toString().equals("Đơn giá")){
                listModel.addElement(Integer.toString(sp.getDongia()));
                this.tbl_table.setModel(listModel);
            }
        }
    }//GEN-LAST:event_cb_suapanelActionPerformed

    private void tbl_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tableMouseClicked
        ClassSanPham sp = spList.get(tbl_table.getSelectedIndex());

        this.lb_masanpham.setText(sp.getMasanpham());
        this.txt_dongia.setText(Integer.toString(sp.getDongia()));
        this.txt_loai.setText(sp.getLoai().toString());
        this.txt_tensanpham.setText(sp.getTensanpham().toString());
    }//GEN-LAST:event_tbl_tableMouseClicked

    private void btn_suapanel_hoantatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suapanel_hoantatActionPerformed

        ClassSanPham sp = spList.get(tbl_table.getSelectedIndex());
        String code = sp.getMasanpham().toString();

        String sql = "UPDATE sanpham SET masanpham=?, loai=?, tensanpham=?, dongia=? WHERE masanpham='"+code+"'";
        System.out.println(sql);
        this.updateDataIntoSanPham(sql);
        listModel.clear();
        spList.clear();
        this.searchDataFromSanPham();
        tbl_table.setModel(listModel);
        for ( ClassSanPham dbl : spList) {
            listModel.addElement(dbl.getMasanpham().toString());
            this.tbl_table.setModel(listModel);
        }
    }//GEN-LAST:event_btn_suapanel_hoantatActionPerformed

    private void btn_suapanel_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suapanel_xoaActionPerformed
        ClassSanPham sp = spList.get(tbl_table.getSelectedIndex());
        String code = sp.getMasanpham().toString();
        System.out.println(code);
        String sql = "DELETE FROM sanpham WHERE masanpham="+code ;

        this.deleteDataInKhachHang(sql);

        listModel.clear();

        spList.clear();
        this.searchDataFromSanPham();
        tbl_table.setModel(listModel);
        for ( ClassSanPham dbl : spList) {
            listModel.addElement(dbl.getMasanpham().toString());
            this.tbl_table.setModel(listModel);
        }
    }//GEN-LAST:event_btn_suapanel_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suapanel_hoantat;
    private javax.swing.JButton btn_suapanel_xoa;
    private javax.swing.JComboBox<String> cb_suapanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_masanpham;
    private javax.swing.JList<String> tbl_table;
    private javax.swing.JTextField txt_dongia;
    private javax.swing.JTextField txt_loai;
    private javax.swing.JTextField txt_tensanpham;
    // End of variables declaration//GEN-END:variables
}
