/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan.java;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoang Nguyen
 */
public class PanelThemKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form PanelThemKhachHang
     */
    public PanelThemKhachHang() {
        initComponents();
        this.loadDataFromKhachHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_thempanel_them = new javax.swing.JButton();
        txt_thempanel_hoten = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_thempanel_sdt = new javax.swing.JTextField();
        txt_thempanel_diachi = new javax.swing.JTextField();
        txt_thempanel_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_thempanel = new javax.swing.JTable();
        cb_thempanel_gioitinh = new javax.swing.JComboBox<>();
        cb_thempanel_loaikhachhang = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 204, 255));

        btn_thempanel_them.setBackground(new java.awt.Color(255, 153, 51));
        btn_thempanel_them.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_thempanel_them.setForeground(new java.awt.Color(51, 0, 255));
        btn_thempanel_them.setText("Thêm");
        btn_thempanel_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thempanel_themActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Tên khách hàng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Số điện thoại");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Địa chỉ ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Email");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Loại khách hàng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Giới tính:");

        tb_thempanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên khách hàng", "Số điện thoại", "Giới tính", "Địa chỉ", "Email", "Loại khách hàng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_thempanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_thempanelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_thempanel);

        cb_thempanel_gioitinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_thempanel_gioitinh.setForeground(new java.awt.Color(255, 102, 51));
        cb_thempanel_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        cb_thempanel_loaikhachhang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_thempanel_loaikhachhang.setForeground(new java.awt.Color(255, 102, 51));
        cb_thempanel_loaikhachhang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng Mới", "Khách hàng thân thiết", "Khách hàng VIP" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_thempanel_hoten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txt_thempanel_sdt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txt_thempanel_diachi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txt_thempanel_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(cb_thempanel_loaikhachhang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cb_thempanel_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 277, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_thempanel_them, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_thempanel_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(cb_thempanel_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_thempanel_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_thempanel_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_thempanel_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_thempanel_loaikhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(btn_thempanel_them, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private String header[] = {"Tên khách hàng", "Số Điện Thoại", "Giới tính", "Địa Chỉ", "Email", "Loại khách hàng"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);

    public void loadDataFromKhachHang() {
        try {
            Connection connection = new dbconnection().connectionDB();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Error connect to database", "Message", JOptionPane.INFORMATION_MESSAGE);
            }
            Statement st = connection.createStatement();

            String sql = "select * from khachhang Order by tenkhachhang";
            ResultSet rs = st.executeQuery(sql);

            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Not Data!", "Message", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            tblModel = new DefaultTableModel(header, 0);
            Vector data = null;
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getString("tenkhachhang"));
                data.add(rs.getString("sdtkhachhang"));
                data.add(rs.getString("gioitinh"));
                data.add(rs.getString("diachi"));
                data.add(rs.getString("email"));
                data.add(rs.getString("loaikhachhang"));
                tblModel.addRow(data);
            }
            tb_thempanel.setModel(tblModel);
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void btn_thempanel_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thempanel_themActionPerformed
        // TODO add your handling code here:
        dbconnection db = new dbconnection();
        String sql = "INSERT INTO khachhang Values('";
        sql += this.txt_thempanel_hoten.getText() + "','";
        sql += this.txt_thempanel_sdt.getText() + "','";
        sql += this.cb_thempanel_gioitinh.getSelectedItem().toString() + "','";
        sql += this.txt_thempanel_diachi.getText() + "','";
        sql += this.txt_thempanel_email.getText() + "','";
        sql += this.cb_thempanel_loaikhachhang.getSelectedItem().toString() + "')";
        System.out.println(sql);
        db.insertDataIntoKhachHang(sql);
        this.loadDataFromKhachHang();
    }//GEN-LAST:event_btn_thempanel_themActionPerformed

    private void tb_thempanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_thempanelMouseClicked
        txt_thempanel_hoten.setText(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 0).toString());
        txt_thempanel_sdt.setText(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 1).toString());
        cb_thempanel_gioitinh.setSelectedItem(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 2).toString());
        txt_thempanel_diachi.setText(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 3).toString());
        txt_thempanel_email.setText(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 4).toString());
        cb_thempanel_loaikhachhang.setSelectedItem(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_tb_thempanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_thempanel_them;
    private javax.swing.JComboBox<String> cb_thempanel_gioitinh;
    private javax.swing.JComboBox<String> cb_thempanel_loaikhachhang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_thempanel;
    private javax.swing.JTextField txt_thempanel_diachi;
    private javax.swing.JTextField txt_thempanel_email;
    private javax.swing.JTextField txt_thempanel_hoten;
    private javax.swing.JTextField txt_thempanel_sdt;
    // End of variables declaration//GEN-END:variables
}
