/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan.java;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *  
 * @author Hoang Nguyen
 */
public class PanelSuaKhachHang extends javax.swing.JPanel {
    private DefaultListModel listModel = new DefaultListModel();
    /**
     * Creates new form PanelSuaKhachHang
     */
    public PanelSuaKhachHang() {
        initComponents();
        this.searchDataFromKhachHang();
        for (ClassKhachHang db : khList) {
            listModel.addElement(db.getTenkhachhang().toString());
            this.tbl_table.setModel(listModel);
        }
    }
    ArrayList<ClassKhachHang> khList = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb_suapanel = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_table = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        btn_suapanel_hoantat = new javax.swing.JButton();
        txt_sua_hoten = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_suapanel_gioitinh = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btn_suapanel_xoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_sua_sdt = new javax.swing.JTextField();
        txt_sua_diachi = new javax.swing.JTextField();
        txt_sua_email = new javax.swing.JTextField();
        cb_suapanel_loaikhachhang = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 255, 204));

        cb_suapanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_suapanel.setForeground(new java.awt.Color(153, 0, 0));
        cb_suapanel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên khách hàng", "Số điện thoại", "Giới Tính", "Email", "Địa chỉ", "Loại khách hàng" }));
        cb_suapanel.setToolTipText("");
        cb_suapanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_suapanelActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Danh Mục");

        tbl_table.setBackground(new java.awt.Color(255, 153, 153));
        tbl_table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_table.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tbl_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_table);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        btn_suapanel_hoantat.setBackground(new java.awt.Color(153, 204, 255));
        btn_suapanel_hoantat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_suapanel_hoantat.setForeground(new java.awt.Color(51, 0, 255));
        btn_suapanel_hoantat.setText("Hoàn tất");
        btn_suapanel_hoantat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suapanel_hoantatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Họ Tên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Số điện thoại");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Giới tính:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Địa chỉ ");

        cb_suapanel_gioitinh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_suapanel_gioitinh.setForeground(new java.awt.Color(255, 102, 51));
        cb_suapanel_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Email");

        btn_suapanel_xoa.setBackground(new java.awt.Color(153, 204, 255));
        btn_suapanel_xoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_suapanel_xoa.setForeground(new java.awt.Color(51, 0, 255));
        btn_suapanel_xoa.setText("Xóa");
        btn_suapanel_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suapanel_xoaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Loại khách hàng");

        cb_suapanel_loaikhachhang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_suapanel_loaikhachhang.setForeground(new java.awt.Color(255, 102, 51));
        cb_suapanel_loaikhachhang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng Mới", "Khách hàng thân thiết", "Khách hàng VIP" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sua_hoten)
                            .addComponent(txt_sua_sdt)
                            .addComponent(txt_sua_diachi)
                            .addComponent(txt_sua_email)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_suapanel_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cb_suapanel_loaikhachhang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_suapanel_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(btn_suapanel_hoantat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sua_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sua_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sua_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sua_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_suapanel_loaikhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cb_suapanel_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_suapanel_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suapanel_hoantat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_suapanel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(81, 81, 81)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(cb_suapanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateDataIntoKhachHang(String sql){
        try {
            Connection connection = new dbconnection().connectionDB();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to DB", JOptionPane.INFORMATION_MESSAGE);
            }            
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, this.txt_sua_hoten.getText());
            pst.setString(2, this.txt_sua_sdt.getText());
            pst.setString(3, this.cb_suapanel_gioitinh.getSelectedItem().toString());
            pst.setString(4, this.txt_sua_diachi.getText());
            pst.setString(5, this.txt_sua_email.getText());
            pst.setString(6, this.cb_suapanel_loaikhachhang.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Updated success", "Message", JOptionPane.INFORMATION_MESSAGE);
            pst.executeUpdate();
            connection.close();
        } catch (Exception e) {
        }
    }
    
    public void searchDataFromKhachHang() {
        try {
            Connection connection = new dbconnection().connectionDB();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to database", JOptionPane.INFORMATION_MESSAGE);
            }
            Statement st = connection.createStatement();
            
            String sql= "SELECT * FROM khachhang ORDER BY tenkhachhang";
            
            ResultSet rs = st.executeQuery(sql);

            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Message", "Not Data!", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            while (rs.next()) {
                ClassKhachHang data = new ClassKhachHang();                
                data.setTenkhachhang(rs.getString("tenkhachhang"));
                data.setSdtkhachhang(rs.getString("sdtkhachhang"));
                data.setGioitinh(rs.getString("gioitinh"));
                data.setDiachi(rs.getString("diachi"));
                data.setEmail(rs.getString("email"));
                data.setLoaikhachhang(rs.getString("loaikhachhang"));
                khList.add(data);
            }
            
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void deleteDataInKhachHang(String sql){
        try {
            Connection conn = new dbconnection().connectionDB();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Message", "Error connect to DB", JOptionPane.INFORMATION_MESSAGE);
            }
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.executeUpdate();
//            DefaultTableModel model =(DefaultTableModel)spList.getClass();
//            model.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Delete success", "Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }
    
    private void cb_suapanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_suapanelActionPerformed
        listModel.clear();

        khList.clear();
        this.searchDataFromKhachHang();
        tbl_table.setModel(listModel);
        for ( ClassKhachHang db : khList) {
            if(cb_suapanel.getSelectedItem().toString().equals("Tên khách hàng")){
                listModel.addElement(db.getTenkhachhang().toString());
                this.tbl_table.setModel(listModel);
            }
            else if(cb_suapanel.getSelectedItem().toString().equals("Loại khách hàng")){
                listModel.addElement(db.getLoaikhachhang().toString());
                this.tbl_table.setModel(listModel);
            }
            else if(cb_suapanel.getSelectedItem().toString().equals("Địa chỉ")){
                listModel.addElement(db.getDiachi().toString());
                this.tbl_table.setModel(listModel);
            }
            else if(cb_suapanel.getSelectedItem().toString().equals("Số điện thoại")){
                listModel.addElement(db.getSdtkhachhang().toString());
                this.tbl_table.setModel(listModel);
            }
            else if(cb_suapanel.getSelectedItem().toString().equals("Giới Tính")){
                listModel.addElement(db.getGioitinh().toString());
                this.tbl_table.setModel(listModel);
            }
            else{
                listModel.addElement(db.getEmail().toString());
                this.tbl_table.setModel(listModel);
            }
        }
    }//GEN-LAST:event_cb_suapanelActionPerformed

    private void tbl_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tableMouseClicked
        ClassKhachHang db = khList.get(tbl_table.getSelectedIndex());

        this.txt_sua_hoten.setText(db.getTenkhachhang().toString());
        this.txt_sua_sdt.setText(db.getSdtkhachhang().toString());
        this.cb_suapanel_gioitinh.setSelectedItem(db.getGioitinh().toString());
        this.txt_sua_diachi.setText(db.getDiachi().toString());
        this.txt_sua_email.setText(db.getEmail().toString());
        this.cb_suapanel_loaikhachhang.setSelectedItem(db.getLoaikhachhang().toString());
    }//GEN-LAST:event_tbl_tableMouseClicked

    private void btn_suapanel_hoantatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suapanel_hoantatActionPerformed

        ClassKhachHang db = khList.get(tbl_table.getSelectedIndex());
        String code = db.getSdtkhachhang().toString();
        System.out.println(code);
        String sql = "UPDATE khachhang SET tenkhachhang=?, sdtkhachhang=?, gioitinh=?, diachi=?, email=?, loaikhachhang=? WHERE sdtkhachhang="+code;

        this.updateDataIntoKhachHang(sql);
        listModel.clear();
        khList.clear();
        this.searchDataFromKhachHang();
        tbl_table.setModel(listModel);
        for ( ClassKhachHang dbl : khList) {
            listModel.addElement(dbl.getTenkhachhang().toString());
            this.tbl_table.setModel(listModel);
        }
    }//GEN-LAST:event_btn_suapanel_hoantatActionPerformed

    private void btn_suapanel_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suapanel_xoaActionPerformed
        ClassKhachHang db = khList.get(tbl_table.getSelectedIndex());
        String code = db.getSdtkhachhang().toString();
        System.out.println(code);
        String sql = "DELETE FROM khachhang WHERE sdtkhachhang="+code ;

        this.deleteDataInKhachHang(sql);
        this.updateDataIntoKhachHang(sql);

        listModel.clear();

        khList.clear();
        this.searchDataFromKhachHang();
        tbl_table.setModel(listModel);
        for ( ClassKhachHang dbl : khList) {
            listModel.addElement(dbl.getTenkhachhang().toString());
            this.tbl_table.setModel(listModel);
        }
    }//GEN-LAST:event_btn_suapanel_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_suapanel_hoantat;
    private javax.swing.JButton btn_suapanel_xoa;
    private javax.swing.JComboBox<String> cb_suapanel;
    private javax.swing.JComboBox<String> cb_suapanel_gioitinh;
    private javax.swing.JComboBox<String> cb_suapanel_loaikhachhang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> tbl_table;
    private javax.swing.JTextField txt_sua_diachi;
    private javax.swing.JTextField txt_sua_email;
    private javax.swing.JTextField txt_sua_hoten;
    private javax.swing.JTextField txt_sua_sdt;
    // End of variables declaration//GEN-END:variables
}
