/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doan.java;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hoang Nguyen
 */
public class PanelThemSanPham extends javax.swing.JPanel {

    /**
     * Creates new form PanelThemSanPham
     */
    public PanelThemSanPham() {
        initComponents();
        loadDataFromKhachHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_tensanpham = new javax.swing.JTextField();
        txt_dongia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_masanpham = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_thempanel = new javax.swing.JTable();
        btn_themsanpham = new javax.swing.JButton();
        txt_loai = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Mã sản phẩm:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Tên sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Đơn giá");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Loại:");

        tb_thempanel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Loại", "Tên sản phẩm", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_thempanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_thempanelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_thempanel);

        btn_themsanpham.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_themsanpham.setForeground(new java.awt.Color(255, 0, 51));
        btn_themsanpham.setText("Thêm sản phẩm");
        btn_themsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themsanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_masanpham, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tensanpham, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_dongia, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txt_loai))
                .addGap(267, 267, 267)
                .addComponent(btn_themsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_masanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tensanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_dongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btn_themsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private String header[] = {"Mã sản phẩm", "Loại", "Tên sản phẩm", "Đơn giá",};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);

    public void loadDataFromKhachHang() {
        try {
            Connection connection = new dbconnection().connectionDB();
            if (connection == null) {
                JOptionPane.showMessageDialog(this, "Error connect to database", "Message", JOptionPane.INFORMATION_MESSAGE);
            }
            Statement st = connection.createStatement();

            String sql = "select * from sanpham";
            ResultSet rs = st.executeQuery(sql);

            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Not Data!", "Message", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            tblModel = new DefaultTableModel(header, 0);
            Vector data = null;
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getString("masanpham"));
                data.add(rs.getString("loai"));
                data.add(rs.getString("tensanpham"));
                data.add(rs.getString("dongia"));
                tblModel.addRow(data);
            }
            tb_thempanel.setModel(tblModel);
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void tb_thempanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_thempanelMouseClicked
        txt_masanpham.setText(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 0).toString());
        txt_tensanpham.setText(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 1).toString());
        txt_loai.setText(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 2).toString());
        txt_dongia.setText(tb_thempanel.getValueAt(tb_thempanel.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tb_thempanelMouseClicked

    private void btn_themsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themsanphamActionPerformed
        dbconnection db = new dbconnection();
        String sql = "INSERT INTO sanpham Values('";
        sql += this.txt_masanpham.getText() + "','";
        sql += this.txt_loai.getText() + "','";
        sql += this.txt_tensanpham.getText()+ "','";
        sql += this.txt_dongia.getText() + "')";
        System.out.println(sql);
        db.insertDataIntoKhachHang(sql);
        this.loadDataFromKhachHang();
    }//GEN-LAST:event_btn_themsanphamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themsanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_thempanel;
    private javax.swing.JTextField txt_dongia;
    private javax.swing.JTextField txt_loai;
    private javax.swing.JTextField txt_masanpham;
    private javax.swing.JTextField txt_tensanpham;
    // End of variables declaration//GEN-END:variables
}
